/// Flutter icons CourseneticsSettings
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CourseneticsSettings
///      fonts:
///       - asset: fonts/CourseneticsSettings.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CourseneticsSettings {
  CourseneticsSettings._();

  static const _kFontFam = 'CourseneticsSettings';
  static const String? _kFontPkg = null;

  static const IconData settings = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
